# Generated by Django 2.2.13 on 2020-06-29 11:35

import cvat.apps.project_submission.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_json', models.FileField(upload_to='submissions/%Y', validators=[django.core.validators.FileExtensionValidator(['json']), cvat.apps.project_submission.validators.validate_json_formatted], verbose_name='Submission JSON')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Submission time')),
                ('ap_lb', models.FloatField(default=None, null=True, verbose_name='Leaderboard MAP')),
                ('ap_total', models.FloatField(default=None, null=True, verbose_name='Total MAP')),
                ('ap50_lb', models.FloatField(default=None, null=True, verbose_name='Leaderboard AP50')),
                ('ap75_lb', models.FloatField(default=None, null=True, verbose_name='Leaderboard AP75')),
                ('aps_lb', models.FloatField(default=None, null=True, verbose_name='Leaderboard AP small')),
                ('apm_lb', models.FloatField(default=None, null=True, verbose_name='Leaderboard AP medium')),
                ('apl_lb', models.FloatField(default=None, null=True, verbose_name='Leaderboard AP large')),
                ('ap50_total', models.FloatField(default=None, null=True, verbose_name='Total AP 50')),
                ('ap75_total', models.FloatField(default=None, null=True, verbose_name='Total AP 75')),
                ('aps_total', models.FloatField(default=None, null=True, verbose_name='Total AP 75')),
                ('apm_total', models.FloatField(default=None, null=True, verbose_name='Total AP 75')),
                ('apl_total', models.FloatField(default=None, null=True, verbose_name='Total AP 75')),
                ('is_solution', models.BooleanField(default=False)),
                ('is_baseline', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Project Submission',
                'verbose_name_plural': 'Project Submissions',
                'ordering': ['-ap_lb', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_on_leaderboard', models.BooleanField(default=True, verbose_name='Show this group on the leaderboard')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_settings', to=settings.AUTH_USER_MODEL, verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Leaderboard Settings',
                'verbose_name_plural': 'Leaderboard Settings',
            },
        ),
    ]
